### PR TITLE
Few improvements to the yaxis legend plugin

### PR DESCRIPTION
**Pull request by mitar**
It allows series to configure if it should be visible in the yaxis legend using its `showRects` option. Provides `showRectsX` and `showRectsY` to offset the legend. Stores `yaxisGroup` and `yaxisRect` into the chart and series, respectively, so that outside code can modify them if needed. Redraw on the `redraw` event, so that dynamically loaded graphs work. And re-bind event handlers so that for series which are loaded after initialization event handlers are bound as well.

### CODE REVIEW

**Comment by mitar** [comment]
All changes are backwards compatible.

**Comment by milmazz** [comment]
@mitar Thanks!, could you please update the following files:

* `package.json`
* `manifest.json`
* `highcharts-legend-yaxis.min.js`

**Comment by mitar** [comment]
You mean I should bump the version and run minimization?

**Comment by milmazz** [comment]
Thanks, great work! :+1:

**Comment by milmazz** [comment]
@mitar I made a few improvements, could you please verify that everything is working correctly? wdyt about the latest changes?

**Comment by mitar** [comment]
Hm, I checked the code, it seems there were only stylistic changes?

**Comment by milmazz** [comment]
Yes, that's right. Thanks for taking the time to review the changes.

**Pull request merged**
